version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: touhou_arrangement_chronicle_development
    ports:
      - '15432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: "./docker/psqldef/Dockerfile"
    volumes:
      - ./db:/app/db
    working_dir: /app
    command:
      - "./psqldef"
      - "--file"
      - "./db/schema/schema.sql"
      - "--host"
      - "db"
      - "--port"
      - "15432"
      - "touhou_arrangement_chronicle_development"
    depends_on:
      - db
    profiles:
      - extra

  seeder:
    image: golang:1.19
    stdin_open: true
    tty: true
    depends_on:
      - db
    profiles:
      - extra
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/touhou_arrangement_chronicle_development?sslmode=disable"
      BUNDEBUG: 1
    volumes:
      - .:/app
    working_dir: /app/go
    command:
      - "go"
      - "run"
      - "cmd/seeder/main.go"

volumes:
  postgres:
