name: test
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'go/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'go/**'
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go/
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - uses: actions/checkout@v3
      - name: testing
        run: go test -race -shuffle=on ./...
